name: CI/CD Pipeline

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

permissions:
  contents: read
  pull-requests: write
  checks: write
  statuses: write

env:
  MAVEN_OPTS: -Dmaven.repo.local=~/.m2/repository

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build & Unit Tests
        run: mvn clean package spring-boot:repackage

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            target/*.jar
            target/surefire-reports/*
            target/site/jacoco/*

      - name: Check Code Format
        run: mvn spotless:check

  code-analysis:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: .

      - name: Generate JaCoCo report
        run: mvn jacoco:report -Djacoco.destFile=target/jacoco.exec

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: target

      - name: List JARs
        run: ls -l target

      - name: Validate JAR manifest
        run: unzip -p target/app.jar META-INF/MANIFEST.MF

      - name: Inspect JAR Manifest
        run: unzip -p target/taller2dosw-0.0.1-SNAPSHOT.jar META-INF/MANIFEST.MF

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'TallerCICD'
          package: 'target/app.jar'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
